language: java

jdk:
  - openjdk8

before_install:
  - mkdir src/main/resources/
  - touch src/main/resources/env.properties
  - printf 'host=%s\nport=%s\nusername=%s\npassword=%s'
    $host $port $username $password  > src/main/resources/env.properties
  - mvn clean
